name: Simple CI Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Проверка содержимого
        run: |
          ls -la
          echo "Проверяем код..."
          echo "CI успешно выполнен!"
